apiVersion: v1
kind: Service
metadata:
  name: ne
  namespace: __namespace__
spec:
  type: ClusterIP
  selector:
    app: ne
  ports:
    - protocol: TCP
      port: 80
      targetPort: 10010
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ne
  namespace: __namespace__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ne
  template:
    metadata:
      labels:
        app: ne
    spec:
      containers:
        - name: ne
          image: "__docker_registry_server__/data.stack:ne.__release__"
          ports:
            - containerPort: 10010
          livenessProbe:
            httpGet:
              path: /ne/internal/health/live
              port: 10010
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ne/internal/health/ready
              port: 10010
            initialDelaySeconds: 10
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: config
      imagePullSecrets:
        - name: regsecret
